apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  annotations:
    uninstall.ocs.openshift.io/cleanup-policy: {{ .Values.uninstallCleanupPolicy}}
    uninstall.ocs.openshift.io/mode: {{ .Values.uninstallMode }}
  name: {{ .Values.storageclusterName }}
  namespace: {{ .Values.storageClusterNamespace }}
spec:
  externalStorage: {}
  flexibleScaling: {{ .Values.flexibleScaling }}
  manageNodes: {{ .Values.manageNodes }}

  resources:
    mds:
      limits:
        cpu: {{ .Values.mdsLimitsCPU }}
        memory: {{ .Values.mdsLimitsMemory }}
      requests:
        cpu: {{ .Values.mdsRequestsCPU }}
        memory: {{ .Values.mdsRequestsMemory }}


  monDataDirHostPath: {{ .Values.monDataDirHostPath }}

  managedResources:
    cephBlockPools:
      reconcileStrategy: {{ .Values.cephBlockPoolsReconcileStrategy }}
    cephFilesystems:
      reconcileStrategy: {{ .Values.cephBlockPoolsReconcileStrategy }}
    cephObjectStoreUsers:
      reconcileStrategy: {{ .Values.cephBlockPoolsReconcileStrategy }}
    cephObjectStores:
      reconcileStrategy: {{ .Values.cephBlockPoolsReconcileStrategy }}
  multiCloudGateway:
    reconcileStrategy: {{ .Values.mcgReconcileStrategy }}


  storageDeviceSets:
    - name: ocs-deviceset-standard
      config: {}
      resources: {}
      placement: {}

      dataPVCTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.storageDiskSize }}
          storageClassName: {{ .Values.diskCountReplica }}
          volumeMode: Block
      count: {{ .Values.diskCount }}
      replica: {{ .Values.diskCountReplica }}
      portable: true
      preparePlacement: {}
