apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  annotations:
    uninstall.ocs.openshift.io/cleanup-policy: {{ .Values.uninstallCleanupPolicy}}
    uninstall.ocs.openshift.io/mode: {{ .Values.uninstallMode }}
  name: {{ .Values.storageclusterName }}
  namespace: {{ .Values.storageClusterNamespace }}
spec:
  externalStorage: {}
  managedResources:
    cephBlockPools:
      reconcileStrategy: {{ .Values.cephBlockPoolsReconcileStrategy }}
    cephFilesystems:
      reconcileStrategy: {{ .Values.cephBlockPoolsReconcileStrategy }}
    cephObjectStoreUsers:
      reconcileStrategy: {{ .Values.cephBlockPoolsReconcileStrategy }}
    cephObjectStores:
      reconcileStrategy: {{ .Values.cephBlockPoolsReconcileStrategy }}
  storageDeviceSets:
    - name: ocs-deviceset-standard
      config: {}
      resources: {}
      placement: {}

      dataPVCTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.storageDiskSize }}
          storageClassName: {{ .Values.diskCountReplica }}
          volumeMode: Block
      count: {{ .Values.diskCount }}
      replica: {{ .Values.diskCountReplica }}
      portable: true
      preparePlacement: {}
