{{- if .Values.namespaceCreate }}
---
# Create openshift-storage namespace.
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: '{{ .Values.clusterMonitoring }}'
  name: {{ template "operator.namespace" $ }}
spec: {}
{{- end }}
